[package]
name = "setheum-primitives"
version = "0.7.3"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
bstringify = "0.1.2"
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
sp-runtime = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
sp-std = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
evm = { version = "0.26.0", default-features = false, features = ["with-codec"] }

[dev-dependencies]
primitives-proc-macro = { path = "./proc-macro" }
serde_json = { version = "1.0.64" }
frame-support = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
	"evm/std",
	"evm/with-serde",
]
