[package]
name = "evm-rpc"
version = "1.0.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-derive = "15.0.0"
ethereum-types = "0.11.0"
rustc-hex = "2.1.0"
serde = { version = "1.0.124", features = ["derive"] }

frame-support = { version = '3.0.0' }
pallet-transaction-payment-rpc-runtime-api = { version = '3.0.0' }
sc-rpc-api = { version = '0.9.0' }
sp-api = { version = '3.0.0' }
sp-blockchain = { version = '3.0.0' }
sp-core = { version = '3.0.0' }
sp-io = { version = '3.0.0' }
sp-rpc = { version = '3.0.0' }
sp-runtime = { version = '3.0.0' }
sp-storage = { version = '3.0.0' }

module-evm-rpc-runtime-api = { path = "runtime_api" }
module-evm = { path = ".." }

[dev-dependencies]
serde_json = "1.0.64"

[features]
default = [ "rpc_binary_search_estimate" ]
rpc_binary_search_estimate = []
