[package]
name = "evm-rpc"
version = "1.0.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-derive = "15.0.0"
ethereum-types = "0.11.0"
rustc-hex = "2.1.0"
serde = { version = "1.0.124", features = ["derive"] }

frame-support = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sc-rpc-api = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-api = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-blockchain = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-core = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-io = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-rpc = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-runtime = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-storage = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }

module-evm-rpc-runtime-api = { path = "runtime_api" }
module-evm = { path = ".." }

[dev-dependencies]
serde_json = "1.0.64"

[features]
default = [ "rpc_binary_search_estimate" ]
rpc_binary_search_estimate = []
