[package]
name = "setcloud-swork"
version = "0.9.70"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
codec = { default-features = false, package = "parity-scale-codec", version = "2.0.0" }
serde = { optional = true, version = "1.0.116" }
base64 = { default-features = false, features = ["alloc"], version = "0.12.2" }
p256 = { default-features = false, features = ["ecdsa"], version = "0.5.1" }

frame-support = { default-features = false, version = "3.0.0" }
frame-system = { default-features = false, version = "3.0.0" }

sp-core = { default-features = false, version = "3.0.0" }
sp-io = { default-features = false, version = "3.0.0" }
sp-runtime = { default-features = false, version = "3.0.0" }
sp-std = { default-features = false, version = "3.0.0" }

primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
webpki = { package = "webpki", path = "../../utils/webpki", default-features = false }
serde_json = { package = "serde_json_no_std", path = "../../utils/serde_json_no_std", default-features = false, features = ["alloc"] }

[dev-dependencies]
keyring = { package = "sp-keyring", version = "3.0.0" }
balances = { package = "module-balances", path = "../balances" }
primitives = { package = "setheum-primitives", path = "../../primitives", features = ["test"] }
market = { package = "setcloud-market", path = "../setcloud-market" }
hex = "0.4.2"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-system/std",
    "primitives/std",
    "webpki/std"
]