[package]
name = "setcloud-swork-benchmarking"
version = "0.9.70"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
codec = { default-features = false, package = "parity-scale-codec", features = ["derive"], version = "2.0.0" }
serde = { optional = true, version = "1.0.116" }

frame-support = { default-features = false, version = "3.0.0" }
frame-system = { default-features = false, version = "3.0.0" }

sp-core = { default-features = false, version = "3.0.0" }
sp-io = { default-features = false, version = "3.0.0" }
sp-runtime = { default-features = false, version = "3.0.0" }
sp-std = { default-features = false, version = "3.0.0" }

frame-benchmarking = { version = "3.0.0", default-features = false }

primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }
market = { package = "setcloud-market", path = "../../setcloud-market", default-features = false }
swork = { package = "setcloud-swork", path = "../../setcloud-swork", default-features = false }
balances = { package = "pallet-balances", version = '3.0.0', default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-system/std",
    "primitives/std",
    "frame-benchmarking/std",
    "swork/std",
    "market/std",
    "balances/std"
]

[dev-dependencies]
hex = "0.4.2"
keyring = { package = "sp-keyring", version = "3.0.0" }
primitives = { package = "setheum-primitives", path = "../../../primitives", features = ["test"] }
