[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'node',
    'lib-serml/*',
    'runtime',
	"runtime/common",
    'primitives',

	"open-lib/auction",
	"open-lib/authority",
	"open-lib/benchmarking",
	"open-lib/currencies",
	"open-lib/nft",
	"open-lib/oracle",
	"open-lib/oracle/rpc",
 	"open-lib/oracle/rpc/runtime-api",
	"open-lib/tokens",
	"open-lib/traits",
	"open-lib/utilities",
	"open-lib/vesting",
	"open-lib/weight-gen",
	"open-lib/weight-meter"
]
exclude = ['rpc']
