[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/fetch-price',
    'pallets/price',
    'pallets/serp-market',
    'pallets/serp-tes',
    'pallets/stp258',
    'runtime',
]
