[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'modules/SERML/fetch-price',
    'modules/SERML/price',
    'modules/SERML/serp-market',
    'modules/SERML/serp-tes',
    'modules/SERML/stp258',
    'runtime',
]
