cargo-features = ["resolver"]

[workspace]
members = [
	"node",
	"node/cli",
	"node/service",

	"lib-serml/airdrop",
	"lib-serml/bridges/*",
	"lib-serml/democracy",
	"lib-serml/dex/*",
	"lib-serml/evm/*",
	"lib-serml/example",
	"lib-serml/prices",
	"lib-serml/serp/*",
	"lib-serml/settmint/*",
	"lib-serml/support",
	"lib-serml/tokens/*",
	"lib-serml/transaction-payment",

	"inspect",
	"primitives",
	"rpc",

	"runtime/common",
	"runtime/newrome",
	"runtime/neom",
	"runtime/setheum",

	"lib-openrml/auction",
	"lib-openrml/authority",
	"lib-openrml/bencher",
	"lib-openrml/benchmarking",
	"lib-openrml/currencies",
	"lib-openrml/nft",
	"lib-openrml/oracle",
	"lib-openrml/oracle/rpc",
 	"lib-openrml/oracle/rpc/runtime-api",
	"lib-openrml/rewards",
	"lib-openrml/tokens",
	"lib-openrml/traits",
	"lib-openrml/utilities",
	"lib-openrml/vesting",
	"lib-openrml/weight-gen",
	"lib-openrml/weight-meter",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
# Setheum runtime requires unwinding.
panic = "unwind"

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# Note that this does **not** affect crates that depend on Substrate. In other words, if you add
# a dependency on Substrate, you have to copy-paste this list in your own `Cargo.toml` (assuming
# that you want the same list). This list is only relevant when running `cargo build` from within
# the Substrate workspace.
#
# If you see an error mentioning "profile package spec ... did not match any packages", it
# probably concerns this list.
#
# This list is ordered alphabetically.
[profile.dev.package]
aes-soft = { opt-level = 3 }
aesni = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake2-rfc = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crossbeam-queue = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hashbrown = { opt-level = 3 }
h2 = { opt-level = 3 }
hash-db = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

# TODO: check to maybe patch this substrate rev d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617

[patch."https://github.com/paritytech/substrate"]
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-benchmarking-cli = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-election-provider-support = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-executive = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-support = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-support-procedural = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-support-procedural-tools = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-support-procedural-tools-derive = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-system = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
frame-try-runtime = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
max-encoded-len = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
max-encoded-len-derive = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-aura = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-authorship = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-babe = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-balances = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-bounties = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-collective = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-democracy = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-grandpa = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-identity = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-im-online = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-indices = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-membership = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-mmr = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-mmr-primitives = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-mmr-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-multisig = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-nicks = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-offences = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-proxy = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-recovery = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-scheduler = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-session = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-society = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-staking = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-sudo = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-timestamp = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-tips = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-transaction-payment = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-treasury = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-utility = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
pallet-vesting = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
remote-externalities = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-basic-authorship = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-block-builder = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-chain-spec = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-cli = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-client-api = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-client-db = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-aura = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-babe = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-epochs = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-consensus-slots = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-executor = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-executor-common = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-executor-wasmtime = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-finality-grandpa = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-informant = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-keystore = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-network = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-network-gossip = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-offchain = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-rpc-api = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-service = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-sync-state-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-telemetry = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-tracing = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sc-transaction-pool = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-allocator = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-block-builder = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-chain-spec = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-consensus = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-consensus-aura = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-consensus-babe = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-consensus-slots = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-consensus-vrf = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-core = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-externalities = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-finality-grandpa = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-inherents = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-io = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-keystore = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-npos-elections = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-offchain = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-rpc = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-runtime = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-serializer = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-session = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-staking = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-state-machine = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-std = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-storage = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-timestamp = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-tracing = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-transaction-pool = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-trie = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-utils = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-version = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
substrate-build-script-utils = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
try-runtime-cli = { git = "https://github.com/paritytech//substrate", rev = "d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617" }
