[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
    'SERML/fetch-price',
    'SERML/price',
    'SERML/serml-traits',
    'SERML/serp-market',
    'SERML/serp-tes',
    'SERML/storage-adapters',
    'SERML/stp258',
]
