version: "3.2"

services:
  dev:
    container_name: setheum-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/setheum-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/setheum-node/.cargo
      - WASM_BUILD_TOOLCHAIN=nightly-2020-10-05
    volumes:
      - .:/var/www/setheum-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/setheum-node --dev --ws-external"
