[package]
name = "setheum-rpc"
version = "0.8.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
jsonrpc-core = "15.0.0"
codec = { package = "parity-scale-codec", version = "2.0.0" }

# Substrate dependencies
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-consensus = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-consensus-babe = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sc-consensus-babe = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-babe-rpc = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-epochs = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-finality-grandpa = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-finality-grandpa-rpc = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-keystore = { version = "0.9.0", git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# orml dependencies
orml-oracle-rpc = { path = "../lib-openrml/oracle/rpc" }

# local dependencies
setheum-evm-rpc = { path = "../lib-serml/evm/evm/rpc" }
runtime-common = { path = "../runtime/common" }
primitives = { package = "setheum-primitives", path = "../primitives" }
