[package]
name = "setheum-service"
version = "0.8.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
async-trait = { version = "0.1.48" }
hex-literal = "0.3.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
futures = "0.3.9"
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.1.0"

# Substrate dependencies
sp-api = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-client-api = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-service = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-executor = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-manual-seal = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-slots = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-network = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-trie = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
substrate-prometheus-endpoint = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-tracing = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-offchain = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-session = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-storage = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-std = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sp-keystore = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# orml dependencies
orml-oracle-rpc = { path = "../../lib-openrml/oracle/rpc" }

# local dependencies
setheum-renvm-bridge = { path = "../../lib-serml/bridges/renvm-bridge" }
setheum-evm = { path = "../../lib-serml/evm/evm" }
setheum-evm-rpc-runtime-api = { path = "../../lib-serml/evm/evm/rpc/runtime_api" }
setheum-rpc = { path = "../../rpc" }
setheum-nft = { path = "../../lib-serml/tokens/nft" }
setheum-primitives = { path = "../../primitives" }

# runtime dependencies
runtime-common = { path = "../../runtime/common" }
newrome-runtime = { path = "../../runtime/newrome", optional = true }
neom-runtime = { path = "../../runtime/neom", optional = true }
setheum-runtime = { path = "../../runtime/setheum", optional = true }

# TODO: consider removing babe
[dev-dependencies]
sc-consensus-babe = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.4" }

[features]
default = [ "std" ]
std = []
runtime-benchmarks = [
	"newrome-runtime/runtime-benchmarks",
	"neom-runtime/runtime-benchmarks",
	"setheum-runtime/runtime-benchmarks",
]
try-runtime = [
	"newrome-runtime/try-runtime",
	"neom-runtime/try-runtime",
	"setheum-runtime/try-runtime",
]
with-newrome-runtime = [
	"newrome-runtime",
]
with-neom-runtime = [
	"neom-runtime",
]
with-setheum-runtime = [
	"setheum-runtime",
]
with-all-runtime = [
	"with-newrome-runtime",
	"with-neom-runtime",
	"with-setheum-runtime",
]
