[package]
name = "setheum-service"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
async-trait = { version = "0.1.48" }
hex-literal = "0.3.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
futures = "0.3.9"
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.1.0"

# Substrate dependencies
sp-api = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-consensus = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-core = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-inherents = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-client-api = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-service = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-executor = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-consensus = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-network = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-cli = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sc-rpc = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-trie = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08"}
sc-tracing = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }

sp-block-builder = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-offchain = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-session = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-storage = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-std = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-keystore = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }

# orml dependencies
orml-oracle-rpc = { path = "../../lib-open/oracle/rpc" }

# local dependencies
setheum-renvm-bridge = { path = "../../lib-serml/bridges/renvm-bridge" }
setheum-evm = { path = "../../lib-serml/evm/evm" }
setheum-evm-rpc-runtime-api = { path = "../../lib-serml/evm/evm/rpc/runtime_api" }
setheum-rpc = { path = "../../rpc" }
setheum-nft = { path = "../../lib-serml/tokens/nft" }
setheum-primitives = { path = "../../primitives" }

# runtime dependencies
runtime-common = { path = "../../runtime/common" }
newrome-runtime = { path = "../../runtime/newrome", optional = true }
setheum-runtime = { path = "../../runtime/setheum", optional = true }

# TODO: consider removing
[dev-dependencies]
sc-consensus-babe = { git = 'https://github.com/paritytech/substrate.git', tag = "monthly-2021-08" }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', tag = "monthly-2021-08" }

[features]
default = [ "std" ]
std = []
runtime-benchmarks = [
	"newrome-runtime/runtime-benchmarks",
	"setheum-runtime/runtime-benchmarks",
]
try-runtime = [
	"newrome-runtime/try-runtime",
	"setheum-runtime/try-runtime",
]
with-newrome-runtime = [
	"newrome-runtime",
]
with-setheum-runtime = [
	"setheum-runtime",
]
with-all-runtime = [
	"with-newrome-runtime",
	"with-setheum-runtime",
]
