[package]
authors = ['Setheum Labs <https://github.com/Setheum-Labs>']
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'setheum-node-runtime'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.3.1-alpha.3'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = { package = 'substrate-wasm-builder-runner', version = '3.0.0' }

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
hex-literal = { optional = true, version = '0.3.1' }
serde = { features = ['derive'], optional = true, version = '1.0.119' }

# local dependencies
stp258 = { version = "0.3.1-alpha.3", default-features = false, path = "pallets/stp258", package = "stp258" }
serp-tes = { version = "0.3.1-alpha.3", default-features = false, path = "pallets/serp-tes", package = "serp-tes" }
serp-market = { version = "0.3.1-alpha.3", default-features = false, path = "pallets/serp-market", package = "serp-market" }
fetch-price = { version = "0.3.1-alpha.3", default-features = false, path = "pallets/fetch-price", package = "fetch-price" }
price = {version = "0.3.1-alpha.3", default-features = false, path = "pallets/price", package = "price"}

# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = '2.0.1' }
frame-executive = { default-features = false, version = '2.0.1' }
frame-support = { default-features = false, version = '2.0.1' }
frame-system = { default-features = false, version = '2.0.1' }
frame-system-benchmarking = { default-features = false, optional = true, version = '2.0.1' }
frame-system-rpc-runtime-api = { default-features = false, version = '2.0.1' }
pallet-aura = { default-features = false, version = '2.0.1' }
pallet-balances = { default-features = false, version = '2.0.1' }
pallet-grandpa = { default-features = false, version = '2.0.1' }
pallet-randomness-collective-flip = { default-features = false, version = '2.0.1' }
pallet-sudo = { default-features = false, version = '2.0.1' }
pallet-timestamp = { default-features = false, version = '2.0.1' }
pallet-transaction-payment = { default-features = false, version = '2.0.1' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '2.0.1' }
sp-api = { default-features = false, version = '2.0.1' }
sp-block-builder = { default-features = false, version = '2.0.1' }
sp-consensus-aura = { default-features = false, version = '0.8.1' }
sp-core = { default-features = false, version = '2.0.1' }
sp-inherents = { default-features = false, version = '2.0.1' }
sp-offchain = { default-features = false, version = '2.0.1' }
sp-runtime = { default-features = false, version = '2.0.1' }
sp-session = { default-features = false, version = '2.0.1' }
sp-std = { default-features = false, version = '2.0.1' }
sp-transaction-pool = { default-features = false, version = '2.0.1' }
sp-version = { default-features = false, version = '2.0.1' }

[features]
default = ['std']
runtime-benchmarks = [
    'hex-literal',
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'codec/std',
    'serde',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'stp258/std',
    'serp-tes/std',
    'serp-market/std',
    'fetch-price/std',
    'price/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
]
