[package]
name = "newrome-runtime"
version = "0.5.0"
authors = ["Setheum Labs"]
edition = "2018"
build = "build.rs"

[dependencies]
# external dependencies
smallvec = "1.4.0"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, default-features = false }
serde_json = "1.0.60"
hex-literal = { version = "0.3.1" }
libsecp256k1 = { version = "0.3.4", default-features = false, optional = true }

# Substrate dependencies
frame-benchmarking = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05', optional = true }
frame-executive = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
frame-support = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
frame-system = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
frame-system-rpc-runtime-api = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-authorship = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-babe = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-balances = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-bounties = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-collective = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-grandpa = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-indices = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-membership = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-multisig = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-offences = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-proxy = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-randomness-collective-flip = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-recovery = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-scheduler = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-session = { version = "3.0.0", features = ["historical"], default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-staking = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-staking-reward-curve = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-sudo = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-timestamp = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-tips = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-treasury = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
pallet-utility = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-api = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-application-crypto = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-block-builder = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-consensus-babe = { version = "0.9.0", default-features = false, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-core = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-inherents = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-io = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-offchain = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-runtime = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-session = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-staking = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-std = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-transaction-pool = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-version = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }

# orml dependencies
orml-auction = { path = "../../lib-orml/auction", default-features = false }
orml-authority = { path = "../../lib-orml/authority", default-features = false }
orml-benchmarking = { path = "../../lib-orml/benchmarking", default-features = false, optional = true }
orml-oracle = { path = "../../lib-orml/oracle", default-features = false }
orml-oracle-rpc-runtime-api = { path = "../../lib-orml/oracle/rpc/runtime-api", default-features = false }
orml-tokens = { path = "../../lib-orml/tokens", default-features = false }
orml-traits = { path = "../../lib-orml/traits", default-features = false }
orml-vesting = { path = "../../lib-orml/vesting", default-features = false }
orml-rewards = { path = "../../lib-orml/rewards", default-features = false }
orml-nft= { path = "../../lib-orml/nft", default-features = false }
orml-unknown-tokens = { path = "../../lib-orml/unknown-tokens", default-features = false }

# local dependencies
setheum-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
setheum-airdrop = { path = "../../lib-serml/airdrop", default-features = false }
serp-auction = { path = "../../lib-serml/serp-auction", default-features = false }
setheum-settmint-engine = { path = "../../lib-serml/settmint-engine", default-features = false }
serp-treasury = { path = "../../lib-serml/serp-treasury", default-features = false }
setheum-dex = { path = "../../lib-serml/dex", default-features = false }
setheum-currencies = { path = "../../lib-serml/currencies", default-features = false }
setheum-settway = { path = "../../lib-serml/settway", default-features = false }
setheum-setters = { path = "../../lib-serml/setters", default-features = false }
setheum-nft = { path = "../../lib-serml/nft", default-features = false }
setheum-prices = { path = "../../lib-serml/prices", default-features = false }
setheum-incentives = { path = "../../lib-serml/incentives", default-features = false }
setheum-support = { path = "../../lib-serml/support", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
runtime-common = { path = "../common", default-features = false }

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dev-dependencies]
libsecp256k1 = "0.3.4"
hex = "0.4.0"

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"serde",

	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-collective/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"orml-auction/std",
	"orml-authority/std",
	"orml-benchmarking/std",
	"orml-oracle-rpc-runtime-api/std",
	"orml-oracle/std",
	"orml-tokens/std",
	"orml-traits/std",
	"orml-vesting/std",
	"orml-rewards/std",
	"orml-nft/std",
	"orml-unknown-tokens/std",

	"setheum-transaction-payment/std",
	"setheum-airdrop/std",
	"serp-auction/std",
	"setheum-settmint-engine/std",
	"serp-treasury/std",
	"setheum-dex/std",
	"setheum-currencies/std",
	"setheum-settway/std",
	"setheum-setters/std",
	"setheum-nft/std",
	"setheum-prices/std",
	"setheum-incentives/std",
	"setheum-support/std",
	"primitives/std",
	"runtime-common/std",

]
runtime-benchmarks = [
	"frame-benchmarking",
	"orml-benchmarking",
	"libsecp256k1/hmac",

	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"orml-authority/runtime-benchmarks",

	"serp-treasury/runtime-benchmarks",
	"setheum-dex/runtime-benchmarks",
]
# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]

try-runtime = [
	"frame-try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system-rpc-runtime-api/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-randomness-collective-flip/try-runtime",
	"pallet-recovery/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-tips/try-runtime",
	"pallet-transaction-payment-rpc-runtime-api/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",

	"orml-auction/try-runtime",
	"orml-authority/try-runtime",
	"orml-oracle-rpc-runtime-api/try-runtime",
	"orml-oracle/try-runtime",
	"orml-tokens/try-runtime",
	"orml-vesting/try-runtime",
	"orml-rewards/stry-runtime",
	"orml-nft/try-runtime",
	"orml-unknown-tokens/try-runtime",

	"setheum-transaction-payment/try-runtime",
	"setheum-airdrop/try-runtime",
	"serp-auction/try-runtime",
	"setheum-settmint-engine/try-runtime",
	"serp-treasury/try-runtime",
	"setheum-currencies/try-runtime",
	"setheum-dex/try-runtime",
	"setheum-settway/try-runtime",
	"setheum-setters/try-runtime",
	"setheum-nft/try-runtime",
	"setheum-prices/try-runtime",
	"setheum-incentives/try-runtime",
	"setheum-support/try-runtime",
	"primitives/try-runtime",
	"runtime-common/try-runtime",
]