[package]
name = "newrome-runtime"
version = "0.7.9"
authors = ["Setheum Labs"]
edition = "2018"
build = "build.rs"

[dependencies]
smallvec = "1.4.0"
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, default-features = false }
serde_json = "1.0.60"
hex-literal = { version = "0.3.1" }

frame-benchmarking = { version = "3.0.0", default-features = false, optional = true }
frame-executive = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-authorship = { version = "3.0.0", default-features = false }
pallet-babe = { version = "3.0.0", default-features = false }
pallet-balances = { version = "3.0.0", default-features = false }
pallet-bounties = { version = "3.0.0", default-features = false }
pallet-collective = { version = "3.0.0", default-features = false }
pallet-elections-phragmen = { version = "3.0.0", default-features = false }
pallet-grandpa = { version = "3.0.0", default-features = false }
pallet-indices = { version = "3.0.0", default-features = false }
pallet-membership = { version = "3.0.0", default-features = false }
pallet-multisig = { version = "3.0.0", default-features = false }
pallet-offences = { version = "3.0.0", default-features = false }
pallet-proxy = { version = "3.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false }
pallet-recovery = { version = "3.0.0", default-features = false }
pallet-scheduler = { version = "3.0.0", default-features = false }
pallet-session = { version = "3.0.0", features = ["historical"], default-features = false }
pallet-staking = { version = "3.0.0", default-features = false }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false }
pallet-sudo = { version = "3.0.0", default-features = false }
pallet-timestamp = { version = "3.0.0", default-features = false }
pallet-tips = { version = "3.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-treasury = { version = "3.0.0", default-features = false }
pallet-utility = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
sp-application-crypto = { version = "3.0.0", default-features = false }
sp-block-builder = { version = "3.0.0", default-features = false }
sp-consensus-babe = { version = "0.9.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-inherents = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-offchain = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-session = { version = "3.0.0", default-features = false }
sp-staking = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-transaction-pool = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }
libsecp256k1 = { version = "0.3.4", default-features = false, optional = true }

orml-auction = { path = "../../lib-orml/auction", default-features = false }
orml-authority = { path = "../../lib-orml/authority", default-features = false }
orml-benchmarking = { path = "../../lib-orml/benchmarking", default-features = false, optional = true }
orml-oracle = { path = "../../lib-orml/oracle", default-features = false }
orml-oracle-rpc-runtime-api = { path = "../../lib-orml/oracle/rpc/runtime-api", default-features = false }
orml-tokens = { path = "../../lib-orml/tokens", default-features = false }
orml-traits = { path = "../../lib-orml/traits", default-features = false }
orml-vesting = { path = "../../lib-orml/vesting", default-features = false }
orml-rewards = { path = "../../lib-orml/rewards", default-features = false }
orml-nft= { path = "../../lib-orml/nft", default-features = false }

setheum-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
setheum-airdrop = { path = "../../lib-serml/airdrop", default-features = false }
setheum-auction-manager = { path = "../../lib-serml/auction-manager", default-features = false }
setheum-settmint-engine = { path = "../../lib-serml/settmint-engine", default-features = false }
serp-treasury = { path = "../../lib-serml/serp-treasury", default-features = false }
setheum-dex = { path = "../../lib-serml/dex", default-features = false }
setheum-currencies = { path = "../../lib-serml/currencies", default-features = false }
setheum-emergency-shutdown = { path = "../../lib-serml/emergency-shutdown", default-features = false }
setheum-settway = { path = "../../lib-serml/settway", default-features = false }
setheum-setters = { path = "../../lib-serml/setters", default-features = false }
setheum-nft = { path = "../../lib-serml/nft", default-features = false }
setheum-prices = { path = "../../lib-serml/prices", default-features = false }
setheum-incentives = { path = "../../lib-serml/incentives", default-features = false }
setheum-support = { path = "../../lib-serml/support", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
runtime-common = { path = "../common", default-features = false }

[build-dependencies]
substrate-wasm-builder = "4.0.0"

[dev-dependencies]
libsecp256k1 = "0.3.4"
hex = "0.4.0"

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"serde",

	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
	"pallet-recovery/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-tips/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",

	"orml-auction/std",
	"orml-authority/std",
	"orml-benchmarking/std",
	"orml-oracle-rpc-runtime-api/std",
	"orml-oracle/std",
	"orml-tokens/std",
	"orml-traits/std",
	"orml-vesting/std",
	"orml-rewards/std",
	"orml-nft/std",

	"setheum-transaction-payment/std",
	"setheum-airdrop/std",
	"setheum-auction-manager/std",
	"setheum-settmint-engine/std",
	"serp-treasury/std",
	"setheum-dex/std",
	"setheum-currencies/std",
	"setheum-emergency-shutdown/std",
	"setheum-settway/std",
	"setheum-setters/std",
	"setheum-nft/std",
	"setheum-prices/std",
	"setheum-incentives/std",
	"setheum-support/std",
	"primitives/std",
	"runtime-common/std",

]
runtime-benchmarks = [
	"frame-benchmarking",
	"orml-benchmarking",
	"libsecp256k1/hmac",

	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"orml-authority/runtime-benchmarks",

	"serp-treasury/runtime-benchmarks",
	"setheum-dex/runtime-benchmarks",
]
# When enabled, the runtime api will not be build.
#
# This is required by Cumulus to access certain types of the
# runtime without clashing with the runtime api exported functions
# in WASM.
disable-runtime-api = []