[package]
name = "serp-ocw"
version = "0.9.1"
authors = ["Setheum Labs"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
serde = { version = "1.0.124", optional = true }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-keystore = { version = "0.9.0", optional = true }
sp-io = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
lite-json = { version = "0.1", default-features = false }
log = { version = "0.4.14", default-features = false }
fixed = { default-features = false, git = "https://github.com/encointer/substrate-fixed", package = "substrate-fixed" }

# orml dependencies
orml-traits = { path = "../../open-lib/traits", default-features = false }
orml-tokens = { path = "../../open-lib/tokens", default-features = false }

# local dependencies
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
support = { package = "module-support", path = "../support", default-features = false }

[dev-dependencies]
sp-core = { version = '3.0.0' }
sp-io = { version = '3.0.0' }
pallet-balances = { version = '3.0.0' }
orml-currencies = { path = "../../open-lib/currencies" }
frame-support = { version = '3.0.0' }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde/std",
	"lite-json/std",
	"log/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-std/std",
	"orml-traits/std",
	"orml-tokens/std",
	"primitives/std",
	"support/std",
]
