[package]
name = "setheum-dev"
version = "0.4.2"
authors = ["Setheum Labs"]
edition = "2018"

[[bin]]
name = "setheum-dev"
path = "src/main.rs"

[dependencies]
futures = "0.3.4"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }
setheum-dev-cli = { path = "cli" }
setheum-dev-service = { path = "service" }

#TODO: This is a workaround for issue https://github.com/bitvecto-rs/bitvec/issues/105. Remove it once fixed.
funty = { version = "=1.1.0" }

[features]
runtime-benchmarks = [
	"setheum-dev-cli/runtime-benchmarks",
]
with-ethereum-compatibility = [
	"setheum-dev-service/with-ethereum-compatibility"
]
with-newrome-runtime = []
