[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'sett stablecoin pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'stp258'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
adapters = { default-features = false, package = 'storage-adapters', version = '0.0.*', path = '../../storage-adapters' }

serde = { version = "1.0.111", optional = true }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }

orml-traits = { default-features = false, version = '0.3.2' }
orml-tokens = { default-features = false, version = '0.3.2' }
orml-utilities = { default-features = false, version = '0.3.2' }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }

[features]
default = ['std']
std = [
	"serde",
    'codec/std',
    'frame-support/std',
    'frame-system/std',
	"orml-traits/std",
    "orml-tokens/std",
    'orml-utilities/std',
]
