[package]
name = "runtime-common"
version = "0.7.1"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true, default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate dependencies
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }
pallet-scheduler = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# orml dependencies
orml-oracle = { path = "../../lib-openrml/oracle", default-features = false }
orml-traits = { path = "../../lib-openrml/traits", default-features = false }

# local dependencies
setheum-support = { path = "../../lib-serml/support", default-features = false }
setheum-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"
hex-literal = "0.3.1"
sp-io = "3.0.0"
pallet-timestamp = "3.0.0"
pallet-balances = "3.0.0"
pallet-proxy = "3.0.0"
pallet-utility = "3.0.0"
orml-tokens = { path = "../../lib-openrml/tokens" }
orml-nft = { path = "../../lib-openrml/nft" }
setheum-currencies = { path = "../../lib-serml/currencies" }
setheum-nft = { path = "../../lib-serml/nft" }
setheum-dex = { path = "../../lib-serml/dex" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-scheduler/std",
	"orml-oracle/std",
	"orml-traits/std",
	"setheum-support/std",
	"primitives/std",
	"setheum-transaction-payment/std",
]
