[package]
name = "runtime-common"
version = '0.9.6'
authors = ["Setheum Developers"]
edition = "2018"

[dependencies]
static_assertions = "1.1.0"
num_enum = { version = "0.5.1", default-features = false }

serde = { version = "1.0.124", optional = true, default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { version = '3.0.0', default-features = false }
sp-core = { version = '3.0.0', default-features = false }
sp-runtime = { version = '3.0.0', default-features = false }
frame-support = { version = '3.0.0', default-features = false }
frame-system = { version = '3.0.0', default-features = false }
pallet-scheduler  = { version = '3.0.0', default-features = false }
pallet-collective = { version = "3.0.0", default-features = false }
pallet-membership = { version = "3.0.0", default-features = false }

module-evm = { path = "../../lib-serml/evm", default-features = false }

orml-oracle = { path = "../../open-lib/oracle", default-features = false }
orml-traits = { path = "../../open-lib/traits", default-features = false }

module-support = { path = "../../lib-serml/support", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
primitives-proc-macro = { path = "../../primitives/proc-macro" }

[dev-dependencies]
serde_json = "1.0.64"
sha3 = { version = "0.9.1" }
hex-literal = "0.3.1"
sp-io = { version = '3.0.0' }
pallet-timestamp = { version = '3.0.0' }
pallet-balances = { version = '3.0.0' }
pallet-proxy = { version = '3.0.0' }
pallet-utility = { version = '3.0.0' }
setheum-node = {  path = "../../node" }
orml-tokens = { path = "../../open-lib/tokens", default-features = false }
module-currencies = { path = "../../lib-serml/currencies" }
module-evm-bridge = { path = "../../lib-serml/evm-bridge" }
module-evm-manager = { path = "../../lib-serml/evm-manager" }
module-nft = { path = "../../lib-serml/nft" }
module-dex = { path = "../../lib-serml/dex" }
module-prices = { path = "../../lib-serml/prices" }
module-transaction-payment = { path = "../../lib-serml/transaction-payment" }


[features]
default = ["std"]
std = [
	"num_enum/std",
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-scheduler/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"module-evm/std",
	"orml-oracle/std",
	"orml-traits/std",
	"module-support/std",
	"primitives/std",
]
with-ethereum-compatibility = [
	"module-evm/with-ethereum-compatibility",
]
