[package]
name = "runtime-common"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
static_assertions = "1.1.0"
num_enum = { version = "0.5.1", default-features = false }
serde = { version = "1.0.101", optional = true, default-features = false }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate dependencies
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-scheduler = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-collective = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev', default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev', default-features = false }

# orml dependencies
orml-oracle = { path = "../../lib-open/oracle", default-features = false }
orml-traits = { path = "../../lib-open/traits", default-features = false }

# local dependencies
setheum-evm = { path = "../../lib-serml/evm/evm", default-features = false }
setheum-support = { path = "../../lib-serml/support", default-features = false }
setheum-transaction-payment = { path = "../../lib-serml/transaction-payment", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
primitives-proc-macro = { path = "../../primitives/proc-macro" }

[dev-dependencies]
serde_json = "1.0.41"
sha3 = { version = "0.9.1" }
hex-literal = "0.3.1"
sp-io = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-balances = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-proxy = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-utility = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
setheum-service = {  path = "../../node/service" }
orml-tokens = { path = "../../lib-open/tokens" }
orml-nft = { path = "../../lib-open/nft" }
setheum-currencies = { path = "../../lib-serml/tokens/currencies" }
setheum-nft = { path = "../../lib-serml/tokens/nft" }
setheum-dex = { path = "../../lib-serml/dex/dex" }
serp-prices = { path = "../../lib-serml/serp/serp-prices" }
setheum-transaction-payment = { path = "../../lib-serml/transaction-payment" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-scheduler/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"orml-oracle/std",
	"orml-traits/std",
	"setheum-support/std",
	"primitives/std",
	"setheum-transaction-payment/std",
]
with-ethereum-compatibility = []
