[package]
name = "setheum-staking-reward-fn"
version = "0.8.0"
authors = ["Setheum Labs"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]

[dependencies]
sp-arithmetic = { version = "3.0.0", default-features = false, path = "../../../primitives/arithmetic" }
log = { version = "0.4.14", default-features = false }

[features]
default = ["std"]
std = [
	"sp-arithmetic/std",
	"log/std",
]
