[package]
name = "setheum-dev-service"
version = "0.7.11"
authors = ["setheum Developers"]
edition = "2018"

[dependencies]
hex-literal = "0.3.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate", branch = "rococo-v1"}

sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

module-evm = { path = "../../../modules/evm" }
module-staking-pool = { path = "../../../modules/staking-pool" }
module-staking-pool-rpc = { path = "../../../modules/staking-pool/rpc" }
module-nft = { path = "../../../modules/nft" }
orml-oracle-rpc = { path = "../../../orml/oracle/rpc" }
setheum-primitives = { path = "../../../primitives" }
setheum-rpc = { path = "../../../rpc", features = ["standalone"]}
module-evm-rpc-runtime-api = { path = "../../../modules/evm/rpc/runtime_api" }

runtime-common = { path = "../../../runtime/common" }
newrome-runtime = { path = "../../../runtime/newrome", features = ["standalone"], optional = true }
Neom-runtime = { path = "../../../runtime/neom", optional = true }
setheum-runtime = { path = "../../../runtime/setheum", optional = true }

[dev-dependencies]
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["test-helpers"] }

[features]
default = ["std", "with-newrome-runtime"]
std = []
runtime-benchmarks = [
	"newrome-runtime/runtime-benchmarks",
	"Neom-runtime/runtime-benchmarks",
	"setheum-runtime/runtime-benchmarks",
]
with-newrome-runtime = [
	"newrome-runtime",
	"newrome-runtime/standalone",
]
with-neom-runtime = [
	"neom-runtime",
]
with-setheum-runtime = [
	"setheum-runtime",
]
with-all-runtime = [
	"with-newrome-runtime",
	"with-neom-runtime",
	"with-setheum-runtime",
]
with-ethereum-compatibility = [
	"newrome-runtime/with-ethereum-compatibility"
]
