[package]
name = "module-nft"
version = "1.0.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
enumflags2 = { version = "0.6.3" }

frame-benchmarking = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false, optional = true}
frame-support = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
frame-system = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
pallet-proxy = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
sp-runtime = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }
sp-std = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6", default-features = false }

orml-nft = { path = "../../open-lib/nft", default-features = false }
orml-traits = { path = "../../open-lib/traits", default-features = false }

[dev-dependencies]
sp-core = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
sp-io = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
pallet-balances = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }
pallet-utility = { git = "https://github.com/Slixon-Technologies/substrate", branch = "newrome-0.9.6" }

orml-tokens = { path = "../../open-lib/tokens" }
module-currencies = { path = "../currencies" }
support = { package = "module-support", path = "../support" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"enumflags2/serde",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-proxy/std",
	"primitives/std",
	"orml-traits/std",
	"orml-nft/std",
	"enumflags2/serde",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
