[package]
name = "setcloud-market"
version = "0.9.70"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
codec = { default-features = false, package = "parity-scale-codec", features = ["derive"], version = "2.0.0" }
serde = { optional = true, version = "1.0.116" }
serde_json = "1.0.51"

frame-system = { default-features = false, version = "3.0.0" }
frame-support = { default-features = false, version = "3.0.0" }

sp-core = { default-features = false, version = "3.0.0" }
sp-io = { default-features = false, version = "3.0.0" }
sp-runtime = { default-features = false, version = "3.0.0" }
sp-std = { default-features = false, version = "3.0.0" }

frame-benchmarking = { default-features = false, optional = true, version = "3.0.0" }

primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-system/std",
    "primitives/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]

[dev-dependencies]
hex = "0.4.2"
swork = { package = "setcloud-swork", path = "../setcloud-swork" }
balances = { package = "pallet-balances", version = '3.0.0' }
primitives = { package = "setheum-primitives", path = "../../primitives", features = ["test"] }
frame-benchmarking = "3.0.0"
