[package]
name = "serp-treasury"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }

# orml dependencies
orml-traits = { path = "../../../lib-open/traits", default-features = false }
orml-tokens = { path = "../../../lib-open/tokens", default-features = false }

# local dependencies
prices = { package = "serp-prices", path = "../../serp/serp-prices", default-features = false }
support = { package = "setheum-support", path = "../../support", default-features = false }
primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
sp-io = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
pallet-balances = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08" }
orml-currencies = { path = "../../../lib-open/currencies" }
setheum-dex = { path = "../../dex/dex" }
orml-tokens = { path = "../../../lib-open/tokens" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-std/std",
	"orml-traits/std",
	"support/std",
	"primitives/std",
]
try-runtime = ["frame-support/try-runtime"]
