[package]
name = "setheum-dev"
version = "0.7.9"
authors = ["Setheum Developers"]
edition = "2018"

[[bin]]
name = "setheum-dev"
path = "src/main.rs"

[dependencies]
futures = "0.3.4"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }
setheum-dev-cli = { path = "cli" }
setheum-dev-service = { path = "service" }

[features]
runtime-benchmarks = [
	"setheum-dev-cli/runtime-benchmarks",
]
with-newrome-runtime = []
