[package]
name = "setheum"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"
default-run = "setheum"

[[bin]]
name = "setheum"
path = "src/main.rs"

[dependencies]
# external dependencies
futures = "0.3.15"
parity-util-mem = { version = "0.9.0", default-features = false, features = ["jemalloc-global"] }

# local dependencies
setheum-cli = { path = "cli" }
setheum-service = { path = "service" }

[features]
default = [ "with-newrome-runtime" ]
runtime-benchmarks = [
	"setheum-cli/runtime-benchmarks",
]
with-newrome-runtime = [
	"setheum-service/with-newrome-runtime",
	"setheum-cli/with-newrome-runtime",
]
with-setheum-runtime = [
	"setheum-service/with-setheum-runtime",
	"setheum-cli/with-setheum-runtime",
]
with-all-runtime = [
	"setheum-service/with-all-runtime",
	"setheum-cli/with-all-runtime",
]
