[package]
authors = ['Setheum Labs <https://github.com/Setheum-Labs>']
build = 'build.rs'
description = 'Setheum Network - Substrate FRAME-based Blockchain, DeFi and Dinar-Sett ready for hacking 🚀'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'node-template'
repository = 'https://github.com/Setheum-Labs/Setheum'
version = '2.0.1'

[[bin]]
name = 'node-template'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '3.0.0'

[dependencies]
jsonrpc-core = '17.0.0'
structopt = '0.3.21'

# local dependencies
node-template-runtime = { path = '../runtime', version = '2.0.1' }
adapters = { default-features = false, package = 'storage-adapters', version = '0.4.1', path = '../../storage-adapters' }
price = { default-features = false, package = 'price', version = '0.4.1', path = '../pallets/price' }
fetch-price = { default-features = false, package = 'fetch-price', version = '0.4.1', path = '../pallets/fetch-price' }
stp258 = { default-features = false, package = 'stp258', version = '0.4.1', path = '../pallets/stp258' }
serp-tes = { default-features = false, package = 'serp-tes', version = '0.4.1', path = '../pallets/serp-tes' }
serp-market = { default-features = false, package = 'serp-tes', version = '0.4.1', path = '../pallets/serp-market' }

# Frontier Dependencies
frontier-consensus = { git = 'https://github.com/PureStake/frontier.git', branch = 'substrate-v2' }
frontier-rpc = { git = 'https://github.com/PureStake/frontier.git', branch = 'substrate-v2' }
frontier-rpc-primitives = { git = 'https://github.com/PureStake/frontier.git', branch = 'substrate-v2' }

# Substrate dependencies
frame-benchmarking = '3.0.0'
frame-benchmarking-cli = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-basic-authorship = '0.9.0'
sc-cli = { features = ['wasmtime'], version = '0.9.0' }
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-aura = '0.9.0'
sc-executor = { features = ['wasmtime'], version = '0.9.0' }
sc-finality-grandpa = '0.9.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = { features = ['wasmtime'], version = '0.9.0' }
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-aura = '0.9.0'
sp-core = '3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'

[features]
default = []
runtime-benchmarks = ['node-template-runtime/runtime-benchmarks']
