[package]
name = "setheum-dev-cli"
version = "0.7.1"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
structopt = "0.3.8"

# Substrate dependencies
sp-core = { version = "3.0.0", optional = true, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sc-cli = { version = "0.9.0", optional = true, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sc-service = { version = "0.9.0", optional = true, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
frame-benchmarking-cli = { version = "3.0.0", optional = true, git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }

# local dependencies
inspect = { package = "setheum-inspect", path = "../../../inspect" }
service = { package = "setheum-dev-service", path = "../service", default-features = false, optional = true }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", default-features = false }

[features]
default = [ "wasmtime", "cli", "with-newrome-runtime" ]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
	"service",
	"sp-core",
	"sc-cli",
	"sc-service",
	"frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
with-newrome-runtime = [
	"service/with-newrome-runtime",
]
with-neom-runtime = [
	"service/with-neom-runtime",
]
with-setheum-runtime = [
	"service/with-setheum-runtime",
]
with-all-runtime = [
	"service/with-all-runtime",
]
