[package]
name = "setheum-setters"
version = "0.5.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate dependencies
frame-system = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
frame-support = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-std = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }
sp-runtime = { default-features = false, version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', tag = 'monthly-2021-05' }

# orml dependencies
orml-traits = { path = "../../lib-orml/traits", default-features = false }
orml-tokens = { path = "../../lib-orml/tokens", default-features = false }

# local dependencies
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }
support = { package = "setheum-support", path = "../support", default-features = false }

[dev-dependencies]
sp-core = "3.0.0"
sp-io = "3.0.0"
pallet-balances = "3.0.0"
orml-currencies = { path = "../../lib-orml/currencies" }
serp-treasury = { package = "serp-treasury", path = "../serp-treasury" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-system/std",
	"frame-support/std",
	"sp-std/std",
	"sp-runtime/std",
	"orml-traits/std",
	"primitives/std",
	"support/std",
	"orml-tokens/std",
]
try-runtime = ["frame-support/try-runtime"]
