[package]
name = "serml-build-script-utils"
description = "Crate with utility functions for `build.rs` scripts."
version = "0.9.70"
authors = ["Setheum Labs"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
platforms = "1.1"
