[package]
name = "setmint-manager"
version = "0.9.0"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
# external dependencies
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"] }

# Substrate dependencies
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }

# orml dependencies
orml-traits = { path = "../../../lib-open/traits", default-features = false }
orml-tokens = { path = "../../../lib-open/tokens", default-features = false }

# local dependencies
primitives = { package = "setheum-primitives", path = "../../../primitives", default-features = false }
support = { package = "setheum-support", path = "../../support", default-features = false }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
sp-io = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
pallet-balances = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }
orml-currencies = { path = "../../../lib-open/currencies" }
serp-treasury = { package = "serp-treasury", path = "../../serp/serp-treasury" }
setheum-dex = { path = "../..//dex/dex" }
frame-support = { git = "https://github.com/paritytech/substrate", tag = "monthly-2021-08", version = '4.0.0-dev' }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-system/std",
	"frame-support/std",
	"sp-std/std",
	"sp-runtime/std",
	"orml-traits/std",
	"primitives/std",
	"support/std",
	"orml-tokens/std",
]
try-runtime = ["frame-support/try-runtime"]
