[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'fetch-price pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'fetch-price'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.4'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.6", default-features = false }
serde = { version = "1.0.119", optional = true }
lite-json = { version = "0.1.3", default-features = false }
# substrate deps
sp-std = { version = "2.0.1", default-features = false }
sc-keystore = { version = "2.0.1", optional = true }
frame-support = { version = "2.0.1", default-features = false}
frame-system = { version = "2.0.1", default-features = false }
[dev-dependencies]
sp-core = { default-features = false, version = "2.0.1" }
sp-io = { default-features = false, version = "2.0.1" }
sp-runtime = { default-features = false, version = "2.0.1" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"lite-json/std",
	"sp-core/std",
	"sp-io/std",
	"sc-keystore",
	"sp-runtime/std",
	"sp-std/std",
]