[package]
name = "airdrop-json"
version = "0.9.80"
authors = ["Setheum Labs"]
edition = "2018"

[dependencies]
primitives = { package = "setheum-primitives", path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"frame-system/std",
]
