name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: make toolchain
    - name: Build
      run: make release
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag setheum-node:$(date +%s)
