name: Rust Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: rustup install nightly
           rustup default nightly
           rustup toolchain install nightly-2021-05-09
           rustup target add wasm32-unknown-unknown --toolchain nightly-2021-05-09
           rustup component add clippy
    - name: Build
      run: make release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/setheum-node
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
