name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: build-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Init
      run: rustup install nightly
           rustup default nightly
           rustup toolchain install nightly-2021-05-09
           rustup target add wasm32-unknown-unknown --toolchain nightly-2021-05-09
           rustup component add clippy
    - name: Build
      run: make build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: test-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Test
      run: make test
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: clippy-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Init
      run: make toolchain
    - name: Clippy
      run: make clippy
