name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2021-06-01
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Build
      run: cargo build --locked --features with-all-runtime
    - name: Install clippy
      run: rustup component add clippy
    - name: Run newrome-runtime clippy
      run: cargo clippy --features with-newrome-runtime -- -D warnings
    - name: Run setheum-runtime clippy
      run: cargo clippy --features with-setheum-runtime -- -D warnings
    - name: Run runtime tests
      run: SKIP_WASM_BUILD= cargo test --all --features with-all-runtime
    - name: Run sevm tests
      run: SKIP_WASM_BUILD= cargo test --all --features with-ethereum-compatibility test_module_evm
      run: SKIP_WASM_BUILD= cargo test --all --features with-ethereum-compatibility should_not_kill_contract_on_transfer_all
      run: SKIP_WASM_BUILD= cargo test --all --features with-ethereum-compatibility schedule_call_precompile_should_work
      run: SKIP_WASM_BUILD= cargo test --all --features with-ethereum-compatibility schedule_call_precompile_should_handle_invalid_input
    - name: Run benchmarking tests
      run: cargo test --features runtime-benchmarks --features with-all-runtime --features --all
    - name: Check benchmarks
      run: SKIP_WASM_BUILD= cargo check --features with-all-runtime --tests --all
      run: SKIP_WASM_BUILD= cargo check --features runtime-benchmarks --no-default-features --target=wasm32-unknown-unknown -p newrome-runtime
      run: SKIP_WASM_BUILD= cargo check --features runtime-benchmarks --no-default-features --target=wasm32-unknown-unknown -p setheum-runtime
