name: Test

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2021-06-01
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Build
      run: make build-all
    - name: Install clippy
      run: rustup component add clippy
    - name: Run newrome-runtime clippy
      run: cargo clippy --features with-newrome-runtime -- -D warnings
    - name: Run neom-runtime clippy
      run: cargo clippy --features with-neom-runtime -- -D warnings
    - name: Run setheum-runtime clippy
      run: cargo clippy --features with-setheum-runtime -- -D warnings
    - name: Run runtime tests
      run: make test-runtimes
    - name: Run sevm tests
      run: make test-sevm
    - name: Run benchmarking tests
      run: make test-benchmarking
    - name: Check benchmarks
      run: make check-benchmarks
